import React from "react";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import HamburgerMenu from "./components/HamburgerMenu";
import { User } from '@prisma/client';

const Home: React.FC<{ userList: User[] }> = () => {
  const { data: sessionData } = useSession();
  const userID = sessionData?.user?.id; // Extract userID here

  return (
    <>
      <Head>
        <title>HearMe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-950">
        <img src="favicon.png" className="w-64 my-2 absolute top-10" alt="Logo"></img>
        {sessionData && <HamburgerMenu />}
        {sessionData && <div className="text-white font-mono font-semibold mb-5 text-lg">Hello, <span className="underline cursor-pointer">{sessionData.user?.name}</span>   welcome to <span className="text-yellow-300">HearMe</span></div>}
        <AuthShowcase userID={userID} />
      </main>
    </>
  );
};

// Modify AuthShowcase to accept userID as a prop
interface AuthShowcaseProps {
  userID?: string;
}

export const AuthShowcase: React.FC<AuthShowcaseProps> = ({ userID }) => {
  const { data: sessionData } = useSession();
  console.log(sessionData);
  console.log(userID);

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      {sessionData &&
        <div>
          {/* Content to show when authenticated */}
        </div>
      }
      <button
        className="rounded-full bg-white px-10 py-3 mt-10 font-mono font-semibold text-black no-underline transition hover:bg-white/50"
        onClick={sessionData ? () => void signOut() : () => void signIn("spotify")}
      >
        {sessionData ? "Sign out" : "Sign in via Spotify"}
      </button>
    </div>
  );
};

export default Home;
